CREATE TABLE "GCG_5778_ReOrderPMax"(
 "PRODUCT_FAMILY" CHAR(10) NOT NULL ,
 "DOMESTIC_RO_POINT" INTEGER,
 "INTNL_RO_POINT" INTEGER,
 "DOMESTIC_MAX" INTEGER,
 "INTNL_MAX" INTEGER,
 "LAST_CHG_DATE" TIMESTAMP,
 "LAST_CHG_USER" CHAR(50));
CREATE UNIQUE INDEX "IND_5778product" USING 0 ON "GCG_5778_ReOrderPMax"("PRODUCT_FAMILY");